### ISSUE TITLE
Roadmap на ближайшие две недели

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#139]
- [x] [20:35:17] m1kc: Сначала #135, естессна.
- [x] [20:42:12] m1kc: А. Ну и, естественно, вместе с #135 закроешь #100.
- [x] [20:35:34] m1kc: #113, благо там немного.
- [ ] [20:35:59] m1kc: #138. Тоже не самое сложное.
- [ ] [20:36:27] m1kc: Дальше, пожалуйста, закрой #127
- [ ] и #128.
- [x] [20:37:26] m1kc: Потом сделай передышку и глянь #131. Меня печалит эта туча ворнингов. Как я понял, там от силы пару строчек поправить.
- [ ] [20:38:57] m1kc: Потом ещё можешь сделать #134. Там нужно просто ответить на вопрос. В качестве ответа, например, подойдёт отчёт профилировщика. Необязательное задание.
- [ ] [20:39:16] m1kc: Ну и, наконец, #137.
- [ ] [20:41:11] m1kc: Если вдруг ты всё это сделаешь очень быстро и задач не останется - #132,
- [x] #102. Если и их сделаешь - я буду дико удивлён, поэтому можешь совершенно спокойно отдыхать до моего прибытия.
